language: go
sudo: false
cache:
  directories:
    - $TRAVIS_BUILD_DIR/gosrc
go:
- 1.7.x
env:
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- go get -v github.com/spf13/hugo && $GOPATH/bin/hugo version
script: make
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make push

