baseURL = "https://chip.codes/"
languageCode = "en-us"
title = "Chip Senkbeil - Projects"
theme = "slate"

publishDir = "public"

[ params ]
Favicon = "favicon.ico"
BackgroundStyle = "#657383"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "software"
tag = "software"
icon = "code"

[[ params.nav ]]
name = "themes"
tag = "themes"
icon = "paint-brush"
